[package]
name = "QuarkGUI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.17.1"
runas = "1.0.0"
winapi = "0.3.9"
