[package]
name = "quark_gui"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.17.1"
runas = "1.0.0"
webbrowser = "0.8.8"
winapi = "0.3.9"
